apiVersion: v2
name: app-chart
description: A Helm chart for Kubernetes

type: application
version: 0.6.0
appVersion: "0.1.0"


dependencies:
  - name: postgresql
    version:  8.1.0
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
    tags:
      - app-database